spring:
  datasource:
    url: jdbc:h2:file:/data/demo
    username: sa
    password: 1234
    driverClassName: org.h2.Driver
  h2:
    console:
      path: /h2-ui
      enabled: 'true'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'true'
validation:
  regex-email: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
  regex-password: (.*)+{6,16}

jwt:
  expiration: 720000
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enable: true
# ruta de swagger
    path: /doc/swagger-ui.html