spring:
  datasource:
    url: jdbc:h2:file:/data/demo
    username: sa
    password: 1234
    driverClassName: org.h2.Driver
  h2:
    console:
      path: /h2-ui
      enabled: 'true'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'true'
validation:
  regex-email: ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}$
  regex-password: ^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d@$!%*?&]{8,}$